CREATE TABLE books(
                      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      isbn varchar(50) UNIQUE NOT NULL,
                      name varchar(100) NOT NULL,
                      serialName varchar(50) NOT NULL ,
                      description varchar(250) NOT NULL
);

CREATE TABLE authors(
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100) NOT NULL UNIQUE,
                        description varchar(250) NOT NULL
);

CREATE TABLE categories(
                           id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE publishers(
                           id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE books_authors(
                              book_id int REFERENCES book(id),
                              author_id int REFERENCES authors(id),
                              PRIMARY KEY(book_id, author_id)
);

CREATE TABLE books_categories(
                                 book_id int REFERENCES book(id),
                                 category_id int REFERENCES categories(id),
                                 PRIMARY KEY(book_id, category_id)
);

CREATE TABLE books_publishers(
                                 book_id int REFERENCES book(id),
                                 publisher_id int REFERENCES publisher(id),
                                 PRIMARY KEY(book_id, publisher_id)
);




CREATE TABLE person(
                         id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         full_name varchar(100) NOT NULL,
                         password varchar(100) NOT NULL,
                         email varchar(100) NOT NULL UNIQUE,
                         role varchar(10) NOT NULL
);

ALTER TABLE books ADD COLUMN user_id int REFERENCES user_lib(id)